sudo: required
services:
  - docker

before_install:
  - docker build -t max/docker-react -f Dockerfile.dev .

script:
  - docker run max/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "<地區>"
  app: "<app name>"
  env: "Docker_env"
  bucket_name: <去service的S3找>
  bucket_path: <app name>
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
